# Generated by Django 5.1.6 on 2025-03-27 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='部门名称')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('radius', models.PositiveIntegerField(default=500, verbose_name='有效半径(米)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'db_table': 'sys_department',
            },
        ),
        migrations.CreateModel(
            name='SysUserDepartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datascreen.sysdepartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.sysuser')),
            ],
            options={
                'db_table': 'sys_user_department',
            },
        ),
    ]
