# Generated by Django 5.1.6 on 2025-03-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SysCompanyLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="位置名称"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="纬度"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="经度"
                    ),
                ),
                (
                    "radius",
                    models.PositiveIntegerField(default=500, verbose_name="有效半径(米)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "db_table": "sys_company_location",
            },
        ),
        migrations.CreateModel(
            name="SysFaceFeature",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("feature", models.BinaryField(verbose_name="人脸特征向量")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_feature",
                        to="user.sysuser",
                    ),
                ),
            ],
            options={
                "db_table": "sys_face_feature",
            },
        ),
        migrations.CreateModel(
            name="SysSecurityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("FACE_REG_SUCCESS", "人脸注册成功"),
                            ("FACE_VERIFY_FAIL", "人脸验证失败"),
                            ("LOCATION_MISMATCH", "位置异常"),
                            ("MULTI_DEVICE_LOGIN", "多设备登录"),
                            ("ACCOUNT_LOCKED", "账户锁定"),
                        ],
                        max_length=20,
                        verbose_name="事件类型",
                    ),
                ),
                ("event_data", models.JSONField(default=dict, verbose_name="事件数据")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="发生时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.sysuser",
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "安全日志",
                "verbose_name_plural": "安全日志",
                "db_table": "sys_security_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SysAttendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "check_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="打卡时间"),
                ),
                ("location", models.CharField(max_length=100, verbose_name="经纬度坐标")),
                ("accuracy", models.FloatField(verbose_name="定位精度(米)")),
                ("is_valid", models.BooleanField(default=False, verbose_name="是否有效")),
                ("face_match_score", models.FloatField(verbose_name="人脸匹配度")),
                ("device_info", models.JSONField(default=dict, verbose_name="设备信息")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="user.sysuser",
                    ),
                ),
            ],
            options={
                "db_table": "sys_attendance",
                "indexes": [
                    models.Index(
                        fields=["user", "check_time"],
                        name="sys_attenda_user_id_606208_idx",
                    )
                ],
            },
        ),
    ]
